# Numpy

In [2]:
import numpy as np
from numpy.random import *

In [3]:
mylist = [1, 2, 3, 5]
arr = np.array(mylist)
print(type(arr))
arr

<class 'numpy.ndarray'>


array([1, 2, 3, 5])

In [4]:
matrix = [[5*i+j+1 for j in range(5)] for i in range(5)]
matrix

[[1, 2, 3, 4, 5],
 [6, 7, 8, 9, 10],
 [11, 12, 13, 14, 15],
 [16, 17, 18, 19, 20],
 [21, 22, 23, 24, 25]]

In [5]:
mat=np.array(matrix)
print(type(mat))
mat.shape

<class 'numpy.ndarray'>


(5, 5)

### arange() function

For integer arguments the function is equivalent to the Python built-in `range` function, but returns an `ndarray` rather than a list.

When using a non-integer step, such as 0.1, the results will often not be consistent. It is better to use `numpy.linspace` for these cases.

In [6]:
np.arange(1, 9, 3)

array([1, 4, 7])

### N dimensional Array (ndarray)

In [7]:
# A 2dimensional array of size 2x3, made of 4byte integer elements
x=np.array([[3*i+j+1 for j in range(3)] for i in range(2)], np.int32)
x

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [8]:
print(type(x))
print(x.shape)
x.dtype

<class 'numpy.ndarray'>
(2, 3)


dtype('int32')

Slicing can produce views of the array.

In [9]:
y = x[:, 1]
y

array([2, 5], dtype=int32)

### Numpy Zeros

```py
np.zeros(shape, dtype)
```
`shape` is an int or a tuple of ints.  
`dtype` is the desired data type for the values in the array, like `numpy.int8` etc, with the default being `numpy.float64`.

In [10]:
# Numpy zeros function
np.zeros((5,), dtype=np.float16)

array([0., 0., 0., 0., 0.], dtype=float16)

In [11]:
np.zeros((2, 3), int)

array([[0, 0, 0],
       [0, 0, 0]])

In [12]:
np.zeros((2, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

A similar function like `np.zeros` is `np.ones`

`linspace()` returns evenly spaced numbers over a specified interval.  
```py
np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
```
`stop` is the ending value of the sequence, unless `endpoint` is set to `False`.  
In that case, we make `num+1` intervals, and exclude the last one containing `stop`.
Note that this changes the step.

```py
numpy.eye(N, M=None, k=0)
```
This returns an `ndarray` whose diagonal elements are 1, rest zero. By default, `M` is taken to be `N`.

In [16]:
identity = np.eye(3, 3)
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.linspace(1, 9, 20, retstep=True)

(array([1.        , 1.42105263, 1.84210526, 2.26315789, 2.68421053,
        3.10526316, 3.52631579, 3.94736842, 4.36842105, 4.78947368,
        5.21052632, 5.63157895, 6.05263158, 6.47368421, 6.89473684,
        7.31578947, 7.73684211, 8.15789474, 8.57894737, 9.        ]),
 0.42105263157894735)

In [ ]:
# start and stop here are array-like, look this up later and try to understand how it works
np.linspace([1, 2], [5, 6], 10)

array([[1.        , 2.        ],
       [1.44444444, 2.44444444],
       [1.88888889, 2.88888889],
       [2.33333333, 3.33333333],
       [2.77777778, 3.77777778],
       [3.22222222, 4.22222222],
       [3.66666667, 4.66666667],
       [4.11111111, 5.11111111],
       [4.55555556, 5.55555556],
       [5.        , 6.        ]])

`random.rand()` returns random numbers from a uniform distribution over `[0, 1)`.  
The arguments passed specify the shape of the returned array.  
For values according to the `Normal` distribution, we use `random.randn()`.  
This is a normal distribution with mean 0 and variance 1. For a normal distribution with $\mu$ and $\sigma^2$, use
```py
sigma^2*np.random.randn(...) + mu
```
`n` here stands for _normal_.

In [19]:
np.random.rand(5)

array([0.53356573, 0.39510242, 0.25234938, 0.70137114, 0.64160611])

`numpy.random.randint(low, high, size)` returns random integers from `[low, high)` in an array of shape specified by the parameter "size".

In [20]:
np.random.randint(10, 25, (3, 3))

array([[14, 23, 16],
       [15, 10, 22],
       [17, 14, 17]])

In [ ]:
np.random.rand(3, 2, 2)

array([[[0.90144826, 0.49303442],
        [0.30395331, 0.43300729]],

       [[0.77348962, 0.9792327 ],
        [0.28103256, 0.70784773]],

       [[0.21111187, 0.50276174],
        [0.97036405, 0.96225812]]])

### Shapes

In [ ]:
x=np.array([1, 2, 3, 4])
y=np.array([[1], [2], [3], [4]])
z=np.array([[1, 2, 3, 4]])
w=np.array([[10], [20]])
[x.shape, y.shape, z.shape, w.shape]

[(4,), (4, 1), (1, 4), (2, 1)]

In [ ]:
np.random.randint([1, 3, 5, 7], [[10], [20]])

array([[ 1,  5,  7,  9],
       [13, 15,  8,  9]])

Here `[1, 3, 5, 7]` is of shape `(4, )`  
`[[10], [20]]` is of shape `(2, 1)`  
Broadcasting of `(4, )` is same as `(1, 4)`, so the common shape is `(2, 4)`.  
Resulting lower bound array is  
```py
[[1, 3, 5, 7],
 [1, 3, 5, 7]]
```
And resulting upper bound array is
```py
[[10, 10, 10, 10], 
 [20, 20, 20, 20]]
```

### Broadcasting

[Doc](https://numpy.org/doc/stable/user/basics.broadcasting.html)  

2 ndarrays of different shapes can be broadcast into a common shape. Some arrays are compatible with each other, while some are not compatible for broadcasting.

**General Rules**  
Numpy compares shapes of 2 ndarrays element-wise. It sharts with trailing (rightmost) dimension and works its way left. 2 dimensions are compatible when

1. they are equal
2. one of them is equal to one

Eg let A = 4d array with shape 8x1x6x1, and B = 3d array with shape 7x1x5, then  
```py
A      (4d array):  8 x 1 x 6 x 1
B      (3d array):      7 x 1 x 5
Result (4d array):  8 x 7 x 6 x 5
```
**Another Example**  
`a.shape` is `(5, 1)`  
`b.shape` is `(1, 6)`  
`c.shape` is `(6, )`  
`d.shape` is `()` (d is a _scalar_)  
Then all of these can be broadcast into an array of shape `(5, 6)`


## Numpy Indexing and Selection

Slicing an array in numpy does not create a copy of the original array, it merely is a reference to the same object. So we can give a new name to a slice of an array, and perform operations upon this slice. The changes will be reflected in the original array too, since numpy does not automatically create copies of arrays, to avoid issues in large data arrays.  

We can explicitly ask for a copy of an array using the `copy()` function.

In [35]:
arr = np.zeros(10, int)
arr[:]=100
arr

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [36]:
arr_slice=arr[:5]
arr_slice[:]=3
arr_slice

array([3, 3, 3, 3, 3])

In [37]:
arr

array([  3,   3,   3,   3,   3, 100, 100, 100, 100, 100])

In [38]:
arr_copy = arr.copy()
arr_copy[5:] = -11
arr_copy, arr

(array([  3,   3,   3,   3,   3, -11, -11, -11, -11, -11]),
 array([  3,   3,   3,   3,   3, 100, 100, 100, 100, 100]))

In [39]:
arr = np.arange(20).reshape(4, 5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [47]:
arr[2:, 1:3]

array([[ 6],
       [ 8],
       [10]])

In [48]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
#Indexing row
arr_2d[1]


array([20, 25, 30])

In [ ]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1, 0]

20

In [51]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

## Conditional Selection

`ndarray[conditional]` will return the elements of the array which for which the corresponding element in the boolean array is `True`.

In [44]:
arr = np.arange(1, 11).reshape(5, 2)
arr

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [45]:
bool_arr = arr > 5
bool_arr
# this is a boolean array that evaluates the expression for every element and assigns True or False to each cell

array([[False, False],
       [False, False],
       [False,  True],
       [ True,  True],
       [ True,  True]])

In [52]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

## Sum